services:
  - docker

script:
  ## Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker build -t udagram-frontend ./udagram-frontend

  ## Tagging
  - docker tag udagram-api-feed cuongnm1805/new-udagram-api-feed:c7n
  - docker tag udagram-api-user cuongnm1805/new-udagram-api-user:c7n
  - docker tag udagram-reverseproxy cuongnm1805/new-udagram-reverseproxy:c7n
  - docker tag udagram-frontend cuongnm1805/new-udagram-frontend:local
  - docker image ls
after_success:
  ## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - docker login -u="manhcuong.vn.1995@gmail.com" -p="Cuong123**"
  - docker push cuongnm1805/new-udagram-api-feed:c7n
  - docker push cuongnm1805/new-udagram-api-user:c7n
  - docker push cuongnm1805/new-udagram-reverseproxy:c7n
  - docker push cuongnm1805/new-udagram-frontend:local
