version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy:c7n
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user:c7n
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed:c7n
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
