version: "3"
services:
  reverseproxy:
    image: reverseproxy:c7n
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: udagram-api-user:c7n
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "Cuong123**"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "cuongnm48-database.cy2swakl8eap.us-east-1.rds.amazonaws.com"
      AWS_REGION: "us-east-1"
      AWS_PROFILE: "default"
      AWS_BUCKET: "cuongnm48-bucket"
      JWT_SECRET: "helloworld"
      URL: "http://aba8e684780b748c08b3a6598091f808-330901272.us-east-1.elb.amazonaws.com:8100"
  backend-feed:
    image: udagram-api-feed:c7n
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: "postgres"
      POSTGRES_PASSWORD: "Cuong123**"
      POSTGRES_DB: "postgres"
      POSTGRES_HOST: "cuongnm48-database.cy2swakl8eap.us-east-1.rds.amazonaws.com"
      AWS_REGION: "us-east-1"
      AWS_PROFILE: "default"
      AWS_BUCKET: "cuongnm48-bucket"
      JWT_SECRET: "helloworld"
      URL: "http://aba8e684780b748c08b3a6598091f808-330901272.us-east-1.elb.amazonaws.com:8100"
  frontend:
    image: udagram-frontend:v6
    ports:
      - "8100:80"
